/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TestErrorsRouteImport } from './routes/test-errors'
import { Route as TeacherportalRouteImport } from './routes/teacherportal'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as StudentportalRouteImport } from './routes/studentportal'
import { Route as StudentServiceRouteImport } from './routes/student-service'
import { Route as PublicSurveysRouteImport } from './routes/public-surveys'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FeaturespageRouteImport } from './routes/featurespage'
import { Route as DirectorAcademicRouteImport } from './routes/director-academic'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DeanRouteImport } from './routes/dean'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentServiceIndexRouteImport } from './routes/student-service.index'
import { Route as GuestIndexRouteImport } from './routes/guest.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as DirectorAcademicIndexRouteImport } from './routes/director-academic.index'
import { Route as DeanIndexRouteImport } from './routes/dean.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentServiceStudentsRouteImport } from './routes/student-service.students'
import { Route as StudentServiceScholarshipsRouteImport } from './routes/student-service.scholarships'
import { Route as StudentServiceReportsRouteImport } from './routes/student-service.reports'
import { Route as StudentServicePopulationsRouteImport } from './routes/student-service.populations'
import { Route as StudentServiceOrientationRouteImport } from './routes/student-service.orientation'
import { Route as StudentServiceInscriptionsRouteImport } from './routes/student-service.inscriptions'
import { Route as StudentServiceHighschoolInfosRouteImport } from './routes/student-service.highschool-infos'
import { Route as StudentServiceDocumentsRouteImport } from './routes/student-service.documents'
import { Route as StudentServiceDashboardRouteImport } from './routes/student-service.dashboard'
import { Route as StudentServiceClubsRouteImport } from './routes/student-service.clubs'
import { Route as StudentServiceActivitiesRouteImport } from './routes/student-service.activities'
import { Route as StudentServiceAbsencesRouteImport } from './routes/student-service.absences'
import { Route as GuestProfileRouteImport } from './routes/guest.profile'
import { Route as GuestDashboardRouteImport } from './routes/guest.dashboard'
import { Route as FinanceWordingRouteImport } from './routes/finance.wording'
import { Route as FinanceFeessheetsRouteImport } from './routes/finance.feessheets'
import { Route as FinanceDashbordRouteImport } from './routes/finance.dashbord'
import { Route as FinanceBanksRouteImport } from './routes/finance.banks'
import { Route as DirectorAcademicDashboardRouteImport } from './routes/director-academic.dashboard'
import { Route as DeanTeachersRouteImport } from './routes/dean.teachers'
import { Route as DeanStudentsRouteImport } from './routes/dean.students'
import { Route as DeanSchedulesRouteImport } from './routes/dean.schedules'
import { Route as DeanResultsRouteImport } from './routes/dean.results'
import { Route as DeanProgressRouteImport } from './routes/dean.progress'
import { Route as DeanProgramsRouteImport } from './routes/dean.programs'
import { Route as DeanExamRouteImport } from './routes/dean.exam'
import { Route as DeanDeliberationsRouteImport } from './routes/dean.deliberations'
import { Route as DeanDashboardRouteImport } from './routes/dean.dashboard'
import { Route as DeanCoursesRouteImport } from './routes/dean.courses'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth.change-password'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSurveysRouteImport } from './routes/admin.surveys'
import { Route as AdminSurveyResponsesRouteImport } from './routes/admin.survey-responses'
import { Route as AdminSurveyBuilderRouteImport } from './routes/admin.survey-builder'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfigsRouteImport } from './routes/admin.configs'
import { Route as AdminAccountReviewRouteImport } from './routes/admin.account-review'
import { Route as AdminAccountRequestedRouteImport } from './routes/admin.account-requested'
import { Route as AdminProgramsIndexRouteImport } from './routes/admin.programs.index'
import { Route as StudentServiceParentsListRouteImport } from './routes/student-service.parents.list'
import { Route as FinancePaymentStudentpaymentdetailsRouteImport } from './routes/finance.payment.studentpaymentdetails'
import { Route as FinancePaymentPaymentpromisesRouteImport } from './routes/finance.payment.paymentpromises'
import { Route as FinancePaymentPaymentplanRouteImport } from './routes/finance.payment.paymentplan'
import { Route as FinancePaymentAddpaymentRouteImport } from './routes/finance.payment.addpayment'
import { Route as Auth2faSetupRouteImport } from './routes/auth.2fa.setup'
import { Route as Auth2faLoginRouteImport } from './routes/auth.2fa.login'
import { Route as AdminProgramsListRouteImport } from './routes/admin.programs.list'
import { Route as AdminProgramsAcademicRouteImport } from './routes/admin.programs.academic'
import { Route as AdminConfigsSecurityRouteImport } from './routes/admin.configs.security'
import { Route as AdminConfigsNotificationsRouteImport } from './routes/admin.configs.notifications'
import { Route as AdminConfigsInterfaceRouteImport } from './routes/admin.configs.interface'
import { Route as AdminConfigsGeneralRouteImport } from './routes/admin.configs.general'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorsRoute = TestErrorsRouteImport.update({
  id: '/test-errors',
  path: '/test-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherportalRoute = TeacherportalRouteImport.update({
  id: '/teacherportal',
  path: '/teacherportal',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentportalRoute = StudentportalRouteImport.update({
  id: '/studentportal',
  path: '/studentportal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServiceRoute = StudentServiceRouteImport.update({
  id: '/student-service',
  path: '/student-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSurveysRoute = PublicSurveysRouteImport.update({
  id: '/public-surveys',
  path: '/public-surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturespageRoute = FeaturespageRouteImport.update({
  id: '/featurespage',
  path: '/featurespage',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorAcademicRoute = DirectorAcademicRouteImport.update({
  id: '/director-academic',
  path: '/director-academic',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DeanRoute = DeanRouteImport.update({
  id: '/dean',
  path: '/dean',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServiceIndexRoute = StudentServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentServiceRoute,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const DirectorAcademicIndexRoute = DirectorAcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorAcademicRoute,
} as any)
const DeanIndexRoute = DeanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeanRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServiceStudentsRoute = StudentServiceStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StudentServiceRoute,
} as any)
const StudentServiceScholarshipsRoute =
  StudentServiceScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceReportsRoute = StudentServiceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StudentServiceRoute,
} as any)
const StudentServicePopulationsRoute =
  StudentServicePopulationsRouteImport.update({
    id: '/populations',
    path: '/populations',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceOrientationRoute =
  StudentServiceOrientationRouteImport.update({
    id: '/orientation',
    path: '/orientation',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceInscriptionsRoute =
  StudentServiceInscriptionsRouteImport.update({
    id: '/inscriptions',
    path: '/inscriptions',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceHighschoolInfosRoute =
  StudentServiceHighschoolInfosRouteImport.update({
    id: '/highschool-infos',
    path: '/highschool-infos',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceDocumentsRoute = StudentServiceDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentServiceRoute,
} as any)
const StudentServiceDashboardRoute = StudentServiceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentServiceRoute,
} as any)
const StudentServiceClubsRoute = StudentServiceClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => StudentServiceRoute,
} as any)
const StudentServiceActivitiesRoute =
  StudentServiceActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const StudentServiceAbsencesRoute = StudentServiceAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => StudentServiceRoute,
} as any)
const GuestProfileRoute = GuestProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GuestRoute,
} as any)
const GuestDashboardRoute = GuestDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuestRoute,
} as any)
const FinanceWordingRoute = FinanceWordingRouteImport.update({
  id: '/wording',
  path: '/wording',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceFeessheetsRoute = FinanceFeessheetsRouteImport.update({
  id: '/feessheets',
  path: '/feessheets',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDashbordRoute = FinanceDashbordRouteImport.update({
  id: '/dashbord',
  path: '/dashbord',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBanksRoute = FinanceBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => FinanceRoute,
} as any)
const DirectorAcademicDashboardRoute =
  DirectorAcademicDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DirectorAcademicRoute,
  } as any)
const DeanTeachersRoute = DeanTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DeanRoute,
} as any)
const DeanStudentsRoute = DeanStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DeanRoute,
} as any)
const DeanSchedulesRoute = DeanSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DeanRoute,
} as any)
const DeanResultsRoute = DeanResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DeanRoute,
} as any)
const DeanProgressRoute = DeanProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DeanRoute,
} as any)
const DeanProgramsRoute = DeanProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DeanRoute,
} as any)
const DeanExamRoute = DeanExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => DeanRoute,
} as any)
const DeanDeliberationsRoute = DeanDeliberationsRouteImport.update({
  id: '/deliberations',
  path: '/deliberations',
  getParentRoute: () => DeanRoute,
} as any)
const DeanDashboardRoute = DeanDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DeanRoute,
} as any)
const DeanCoursesRoute = DeanCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DeanRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysRoute = AdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveyResponsesRoute = AdminSurveyResponsesRouteImport.update({
  id: '/survey-responses',
  path: '/survey-responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveyBuilderRoute = AdminSurveyBuilderRouteImport.update({
  id: '/survey-builder',
  path: '/survey-builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigsRoute = AdminConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountReviewRoute = AdminAccountReviewRouteImport.update({
  id: '/account-review',
  path: '/account-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRequestedRoute = AdminAccountRequestedRouteImport.update({
  id: '/account-requested',
  path: '/account-requested',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsIndexRoute = AdminProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const StudentServiceParentsListRoute =
  StudentServiceParentsListRouteImport.update({
    id: '/parents/list',
    path: '/parents/list',
    getParentRoute: () => StudentServiceRoute,
  } as any)
const FinancePaymentStudentpaymentdetailsRoute =
  FinancePaymentStudentpaymentdetailsRouteImport.update({
    id: '/payment/studentpaymentdetails',
    path: '/payment/studentpaymentdetails',
    getParentRoute: () => FinanceRoute,
  } as any)
const FinancePaymentPaymentpromisesRoute =
  FinancePaymentPaymentpromisesRouteImport.update({
    id: '/payment/paymentpromises',
    path: '/payment/paymentpromises',
    getParentRoute: () => FinanceRoute,
  } as any)
const FinancePaymentPaymentplanRoute =
  FinancePaymentPaymentplanRouteImport.update({
    id: '/payment/paymentplan',
    path: '/payment/paymentplan',
    getParentRoute: () => FinanceRoute,
  } as any)
const FinancePaymentAddpaymentRoute =
  FinancePaymentAddpaymentRouteImport.update({
    id: '/payment/addpayment',
    path: '/payment/addpayment',
    getParentRoute: () => FinanceRoute,
  } as any)
const Auth2faSetupRoute = Auth2faSetupRouteImport.update({
  id: '/auth/2fa/setup',
  path: '/auth/2fa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth2faLoginRoute = Auth2faLoginRouteImport.update({
  id: '/auth/2fa/login',
  path: '/auth/2fa/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsListRoute = AdminProgramsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const AdminProgramsAcademicRoute = AdminProgramsAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const AdminConfigsSecurityRoute = AdminConfigsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminConfigsRoute,
} as any)
const AdminConfigsNotificationsRoute =
  AdminConfigsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminConfigsRoute,
  } as any)
const AdminConfigsInterfaceRoute = AdminConfigsInterfaceRouteImport.update({
  id: '/interface',
  path: '/interface',
  getParentRoute: () => AdminConfigsRoute,
} as any)
const AdminConfigsGeneralRoute = AdminConfigsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminConfigsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dean': typeof DeanRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/director-academic': typeof DirectorAcademicRouteWithChildren
  '/featurespage': typeof FeaturespageRoute
  '/finance': typeof FinanceRouteWithChildren
  '/guest': typeof GuestRouteWithChildren
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/public-surveys': typeof PublicSurveysRoute
  '/student-service': typeof StudentServiceRouteWithChildren
  '/studentportal': typeof StudentportalRoute
  '/survey': typeof SurveyRoute
  '/teacherportal': typeof TeacherportalRoute
  '/test-errors': typeof TestErrorsRoute
  '/timetable': typeof TimetableRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/account-requested': typeof AdminAccountRequestedRoute
  '/admin/account-review': typeof AdminAccountReviewRoute
  '/admin/configs': typeof AdminConfigsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/programs': typeof AdminProgramsRouteWithChildren
  '/admin/survey-builder': typeof AdminSurveyBuilderRoute
  '/admin/survey-responses': typeof AdminSurveyResponsesRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dean/courses': typeof DeanCoursesRoute
  '/dean/dashboard': typeof DeanDashboardRoute
  '/dean/deliberations': typeof DeanDeliberationsRoute
  '/dean/exam': typeof DeanExamRoute
  '/dean/programs': typeof DeanProgramsRoute
  '/dean/progress': typeof DeanProgressRoute
  '/dean/results': typeof DeanResultsRoute
  '/dean/schedules': typeof DeanSchedulesRoute
  '/dean/students': typeof DeanStudentsRoute
  '/dean/teachers': typeof DeanTeachersRoute
  '/director-academic/dashboard': typeof DirectorAcademicDashboardRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/dashbord': typeof FinanceDashbordRoute
  '/finance/feessheets': typeof FinanceFeessheetsRoute
  '/finance/wording': typeof FinanceWordingRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest/profile': typeof GuestProfileRoute
  '/student-service/absences': typeof StudentServiceAbsencesRoute
  '/student-service/activities': typeof StudentServiceActivitiesRoute
  '/student-service/clubs': typeof StudentServiceClubsRoute
  '/student-service/dashboard': typeof StudentServiceDashboardRoute
  '/student-service/documents': typeof StudentServiceDocumentsRoute
  '/student-service/highschool-infos': typeof StudentServiceHighschoolInfosRoute
  '/student-service/inscriptions': typeof StudentServiceInscriptionsRoute
  '/student-service/orientation': typeof StudentServiceOrientationRoute
  '/student-service/populations': typeof StudentServicePopulationsRoute
  '/student-service/reports': typeof StudentServiceReportsRoute
  '/student-service/scholarships': typeof StudentServiceScholarshipsRoute
  '/student-service/students': typeof StudentServiceStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/director-academic/': typeof DirectorAcademicIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/student-service/': typeof StudentServiceIndexRoute
  '/admin/configs/general': typeof AdminConfigsGeneralRoute
  '/admin/configs/interface': typeof AdminConfigsInterfaceRoute
  '/admin/configs/notifications': typeof AdminConfigsNotificationsRoute
  '/admin/configs/security': typeof AdminConfigsSecurityRoute
  '/admin/programs/academic': typeof AdminProgramsAcademicRoute
  '/admin/programs/list': typeof AdminProgramsListRoute
  '/auth/2fa/login': typeof Auth2faLoginRoute
  '/auth/2fa/setup': typeof Auth2faSetupRoute
  '/finance/payment/addpayment': typeof FinancePaymentAddpaymentRoute
  '/finance/payment/paymentplan': typeof FinancePaymentPaymentplanRoute
  '/finance/payment/paymentpromises': typeof FinancePaymentPaymentpromisesRoute
  '/finance/payment/studentpaymentdetails': typeof FinancePaymentStudentpaymentdetailsRoute
  '/student-service/parents/list': typeof StudentServiceParentsListRoute
  '/admin/programs/': typeof AdminProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development': typeof DevelopmentRoute
  '/featurespage': typeof FeaturespageRoute
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/public-surveys': typeof PublicSurveysRoute
  '/studentportal': typeof StudentportalRoute
  '/survey': typeof SurveyRoute
  '/teacherportal': typeof TeacherportalRoute
  '/test-errors': typeof TestErrorsRoute
  '/timetable': typeof TimetableRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/account-requested': typeof AdminAccountRequestedRoute
  '/admin/account-review': typeof AdminAccountReviewRoute
  '/admin/configs': typeof AdminConfigsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/survey-builder': typeof AdminSurveyBuilderRoute
  '/admin/survey-responses': typeof AdminSurveyResponsesRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dean/courses': typeof DeanCoursesRoute
  '/dean/dashboard': typeof DeanDashboardRoute
  '/dean/deliberations': typeof DeanDeliberationsRoute
  '/dean/exam': typeof DeanExamRoute
  '/dean/programs': typeof DeanProgramsRoute
  '/dean/progress': typeof DeanProgressRoute
  '/dean/results': typeof DeanResultsRoute
  '/dean/schedules': typeof DeanSchedulesRoute
  '/dean/students': typeof DeanStudentsRoute
  '/dean/teachers': typeof DeanTeachersRoute
  '/director-academic/dashboard': typeof DirectorAcademicDashboardRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/dashbord': typeof FinanceDashbordRoute
  '/finance/feessheets': typeof FinanceFeessheetsRoute
  '/finance/wording': typeof FinanceWordingRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest/profile': typeof GuestProfileRoute
  '/student-service/absences': typeof StudentServiceAbsencesRoute
  '/student-service/activities': typeof StudentServiceActivitiesRoute
  '/student-service/clubs': typeof StudentServiceClubsRoute
  '/student-service/dashboard': typeof StudentServiceDashboardRoute
  '/student-service/documents': typeof StudentServiceDocumentsRoute
  '/student-service/highschool-infos': typeof StudentServiceHighschoolInfosRoute
  '/student-service/inscriptions': typeof StudentServiceInscriptionsRoute
  '/student-service/orientation': typeof StudentServiceOrientationRoute
  '/student-service/populations': typeof StudentServicePopulationsRoute
  '/student-service/reports': typeof StudentServiceReportsRoute
  '/student-service/scholarships': typeof StudentServiceScholarshipsRoute
  '/student-service/students': typeof StudentServiceStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/dean': typeof DeanIndexRoute
  '/director-academic': typeof DirectorAcademicIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/guest': typeof GuestIndexRoute
  '/student-service': typeof StudentServiceIndexRoute
  '/admin/configs/general': typeof AdminConfigsGeneralRoute
  '/admin/configs/interface': typeof AdminConfigsInterfaceRoute
  '/admin/configs/notifications': typeof AdminConfigsNotificationsRoute
  '/admin/configs/security': typeof AdminConfigsSecurityRoute
  '/admin/programs/academic': typeof AdminProgramsAcademicRoute
  '/admin/programs/list': typeof AdminProgramsListRoute
  '/auth/2fa/login': typeof Auth2faLoginRoute
  '/auth/2fa/setup': typeof Auth2faSetupRoute
  '/finance/payment/addpayment': typeof FinancePaymentAddpaymentRoute
  '/finance/payment/paymentplan': typeof FinancePaymentPaymentplanRoute
  '/finance/payment/paymentpromises': typeof FinancePaymentPaymentpromisesRoute
  '/finance/payment/studentpaymentdetails': typeof FinancePaymentStudentpaymentdetailsRoute
  '/student-service/parents/list': typeof StudentServiceParentsListRoute
  '/admin/programs': typeof AdminProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dean': typeof DeanRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/director-academic': typeof DirectorAcademicRouteWithChildren
  '/featurespage': typeof FeaturespageRoute
  '/finance': typeof FinanceRouteWithChildren
  '/guest': typeof GuestRouteWithChildren
  '/home': typeof HomeRoute
  '/not-found': typeof NotFoundRoute
  '/public-surveys': typeof PublicSurveysRoute
  '/student-service': typeof StudentServiceRouteWithChildren
  '/studentportal': typeof StudentportalRoute
  '/survey': typeof SurveyRoute
  '/teacherportal': typeof TeacherportalRoute
  '/test-errors': typeof TestErrorsRoute
  '/timetable': typeof TimetableRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/account-requested': typeof AdminAccountRequestedRoute
  '/admin/account-review': typeof AdminAccountReviewRoute
  '/admin/configs': typeof AdminConfigsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/programs': typeof AdminProgramsRouteWithChildren
  '/admin/survey-builder': typeof AdminSurveyBuilderRoute
  '/admin/survey-responses': typeof AdminSurveyResponsesRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dean/courses': typeof DeanCoursesRoute
  '/dean/dashboard': typeof DeanDashboardRoute
  '/dean/deliberations': typeof DeanDeliberationsRoute
  '/dean/exam': typeof DeanExamRoute
  '/dean/programs': typeof DeanProgramsRoute
  '/dean/progress': typeof DeanProgressRoute
  '/dean/results': typeof DeanResultsRoute
  '/dean/schedules': typeof DeanSchedulesRoute
  '/dean/students': typeof DeanStudentsRoute
  '/dean/teachers': typeof DeanTeachersRoute
  '/director-academic/dashboard': typeof DirectorAcademicDashboardRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/dashbord': typeof FinanceDashbordRoute
  '/finance/feessheets': typeof FinanceFeessheetsRoute
  '/finance/wording': typeof FinanceWordingRoute
  '/guest/dashboard': typeof GuestDashboardRoute
  '/guest/profile': typeof GuestProfileRoute
  '/student-service/absences': typeof StudentServiceAbsencesRoute
  '/student-service/activities': typeof StudentServiceActivitiesRoute
  '/student-service/clubs': typeof StudentServiceClubsRoute
  '/student-service/dashboard': typeof StudentServiceDashboardRoute
  '/student-service/documents': typeof StudentServiceDocumentsRoute
  '/student-service/highschool-infos': typeof StudentServiceHighschoolInfosRoute
  '/student-service/inscriptions': typeof StudentServiceInscriptionsRoute
  '/student-service/orientation': typeof StudentServiceOrientationRoute
  '/student-service/populations': typeof StudentServicePopulationsRoute
  '/student-service/reports': typeof StudentServiceReportsRoute
  '/student-service/scholarships': typeof StudentServiceScholarshipsRoute
  '/student-service/students': typeof StudentServiceStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/director-academic/': typeof DirectorAcademicIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/student-service/': typeof StudentServiceIndexRoute
  '/admin/configs/general': typeof AdminConfigsGeneralRoute
  '/admin/configs/interface': typeof AdminConfigsInterfaceRoute
  '/admin/configs/notifications': typeof AdminConfigsNotificationsRoute
  '/admin/configs/security': typeof AdminConfigsSecurityRoute
  '/admin/programs/academic': typeof AdminProgramsAcademicRoute
  '/admin/programs/list': typeof AdminProgramsListRoute
  '/auth/2fa/login': typeof Auth2faLoginRoute
  '/auth/2fa/setup': typeof Auth2faSetupRoute
  '/finance/payment/addpayment': typeof FinancePaymentAddpaymentRoute
  '/finance/payment/paymentplan': typeof FinancePaymentPaymentplanRoute
  '/finance/payment/paymentpromises': typeof FinancePaymentPaymentpromisesRoute
  '/finance/payment/studentpaymentdetails': typeof FinancePaymentStudentpaymentdetailsRoute
  '/student-service/parents/list': typeof StudentServiceParentsListRoute
  '/admin/programs/': typeof AdminProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dean'
    | '/development'
    | '/director-academic'
    | '/featurespage'
    | '/finance'
    | '/guest'
    | '/home'
    | '/not-found'
    | '/public-surveys'
    | '/student-service'
    | '/studentportal'
    | '/survey'
    | '/teacherportal'
    | '/test-errors'
    | '/timetable'
    | '/unauthorized'
    | '/admin/account-requested'
    | '/admin/account-review'
    | '/admin/configs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/programs'
    | '/admin/survey-builder'
    | '/admin/survey-responses'
    | '/admin/surveys'
    | '/admin/users'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dean/courses'
    | '/dean/dashboard'
    | '/dean/deliberations'
    | '/dean/exam'
    | '/dean/programs'
    | '/dean/progress'
    | '/dean/results'
    | '/dean/schedules'
    | '/dean/students'
    | '/dean/teachers'
    | '/director-academic/dashboard'
    | '/finance/banks'
    | '/finance/dashbord'
    | '/finance/feessheets'
    | '/finance/wording'
    | '/guest/dashboard'
    | '/guest/profile'
    | '/student-service/absences'
    | '/student-service/activities'
    | '/student-service/clubs'
    | '/student-service/dashboard'
    | '/student-service/documents'
    | '/student-service/highschool-infos'
    | '/student-service/inscriptions'
    | '/student-service/orientation'
    | '/student-service/populations'
    | '/student-service/reports'
    | '/student-service/scholarships'
    | '/student-service/students'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/admin/'
    | '/dean/'
    | '/director-academic/'
    | '/finance/'
    | '/guest/'
    | '/student-service/'
    | '/admin/configs/general'
    | '/admin/configs/interface'
    | '/admin/configs/notifications'
    | '/admin/configs/security'
    | '/admin/programs/academic'
    | '/admin/programs/list'
    | '/auth/2fa/login'
    | '/auth/2fa/setup'
    | '/finance/payment/addpayment'
    | '/finance/payment/paymentplan'
    | '/finance/payment/paymentpromises'
    | '/finance/payment/studentpaymentdetails'
    | '/student-service/parents/list'
    | '/admin/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development'
    | '/featurespage'
    | '/home'
    | '/not-found'
    | '/public-surveys'
    | '/studentportal'
    | '/survey'
    | '/teacherportal'
    | '/test-errors'
    | '/timetable'
    | '/unauthorized'
    | '/admin/account-requested'
    | '/admin/account-review'
    | '/admin/configs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/survey-builder'
    | '/admin/survey-responses'
    | '/admin/surveys'
    | '/admin/users'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dean/courses'
    | '/dean/dashboard'
    | '/dean/deliberations'
    | '/dean/exam'
    | '/dean/programs'
    | '/dean/progress'
    | '/dean/results'
    | '/dean/schedules'
    | '/dean/students'
    | '/dean/teachers'
    | '/director-academic/dashboard'
    | '/finance/banks'
    | '/finance/dashbord'
    | '/finance/feessheets'
    | '/finance/wording'
    | '/guest/dashboard'
    | '/guest/profile'
    | '/student-service/absences'
    | '/student-service/activities'
    | '/student-service/clubs'
    | '/student-service/dashboard'
    | '/student-service/documents'
    | '/student-service/highschool-infos'
    | '/student-service/inscriptions'
    | '/student-service/orientation'
    | '/student-service/populations'
    | '/student-service/reports'
    | '/student-service/scholarships'
    | '/student-service/students'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/admin'
    | '/dean'
    | '/director-academic'
    | '/finance'
    | '/guest'
    | '/student-service'
    | '/admin/configs/general'
    | '/admin/configs/interface'
    | '/admin/configs/notifications'
    | '/admin/configs/security'
    | '/admin/programs/academic'
    | '/admin/programs/list'
    | '/auth/2fa/login'
    | '/auth/2fa/setup'
    | '/finance/payment/addpayment'
    | '/finance/payment/paymentplan'
    | '/finance/payment/paymentpromises'
    | '/finance/payment/studentpaymentdetails'
    | '/student-service/parents/list'
    | '/admin/programs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dean'
    | '/development'
    | '/director-academic'
    | '/featurespage'
    | '/finance'
    | '/guest'
    | '/home'
    | '/not-found'
    | '/public-surveys'
    | '/student-service'
    | '/studentportal'
    | '/survey'
    | '/teacherportal'
    | '/test-errors'
    | '/timetable'
    | '/unauthorized'
    | '/admin/account-requested'
    | '/admin/account-review'
    | '/admin/configs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/programs'
    | '/admin/survey-builder'
    | '/admin/survey-responses'
    | '/admin/surveys'
    | '/admin/users'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dean/courses'
    | '/dean/dashboard'
    | '/dean/deliberations'
    | '/dean/exam'
    | '/dean/programs'
    | '/dean/progress'
    | '/dean/results'
    | '/dean/schedules'
    | '/dean/students'
    | '/dean/teachers'
    | '/director-academic/dashboard'
    | '/finance/banks'
    | '/finance/dashbord'
    | '/finance/feessheets'
    | '/finance/wording'
    | '/guest/dashboard'
    | '/guest/profile'
    | '/student-service/absences'
    | '/student-service/activities'
    | '/student-service/clubs'
    | '/student-service/dashboard'
    | '/student-service/documents'
    | '/student-service/highschool-infos'
    | '/student-service/inscriptions'
    | '/student-service/orientation'
    | '/student-service/populations'
    | '/student-service/reports'
    | '/student-service/scholarships'
    | '/student-service/students'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/admin/'
    | '/dean/'
    | '/director-academic/'
    | '/finance/'
    | '/guest/'
    | '/student-service/'
    | '/admin/configs/general'
    | '/admin/configs/interface'
    | '/admin/configs/notifications'
    | '/admin/configs/security'
    | '/admin/programs/academic'
    | '/admin/programs/list'
    | '/auth/2fa/login'
    | '/auth/2fa/setup'
    | '/finance/payment/addpayment'
    | '/finance/payment/paymentplan'
    | '/finance/payment/paymentpromises'
    | '/finance/payment/studentpaymentdetails'
    | '/student-service/parents/list'
    | '/admin/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DeanRoute: typeof DeanRouteWithChildren
  DevelopmentRoute: typeof DevelopmentRoute
  DirectorAcademicRoute: typeof DirectorAcademicRouteWithChildren
  FeaturespageRoute: typeof FeaturespageRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  HomeRoute: typeof HomeRoute
  NotFoundRoute: typeof NotFoundRoute
  PublicSurveysRoute: typeof PublicSurveysRoute
  StudentServiceRoute: typeof StudentServiceRouteWithChildren
  StudentportalRoute: typeof StudentportalRoute
  SurveyRoute: typeof SurveyRoute
  TeacherportalRoute: typeof TeacherportalRoute
  TestErrorsRoute: typeof TestErrorsRoute
  TimetableRoute: typeof TimetableRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  Auth2faLoginRoute: typeof Auth2faLoginRoute
  Auth2faSetupRoute: typeof Auth2faSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-errors': {
      id: '/test-errors'
      path: '/test-errors'
      fullPath: '/test-errors'
      preLoaderRoute: typeof TestErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacherportal': {
      id: '/teacherportal'
      path: '/teacherportal'
      fullPath: '/teacherportal'
      preLoaderRoute: typeof TeacherportalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentportal': {
      id: '/studentportal'
      path: '/studentportal'
      fullPath: '/studentportal'
      preLoaderRoute: typeof StudentportalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-service': {
      id: '/student-service'
      path: '/student-service'
      fullPath: '/student-service'
      preLoaderRoute: typeof StudentServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-surveys': {
      id: '/public-surveys'
      path: '/public-surveys'
      fullPath: '/public-surveys'
      preLoaderRoute: typeof PublicSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featurespage': {
      id: '/featurespage'
      path: '/featurespage'
      fullPath: '/featurespage'
      preLoaderRoute: typeof FeaturespageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director-academic': {
      id: '/director-academic'
      path: '/director-academic'
      fullPath: '/director-academic'
      preLoaderRoute: typeof DirectorAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dean': {
      id: '/dean'
      path: '/dean'
      fullPath: '/dean'
      preLoaderRoute: typeof DeanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-service/': {
      id: '/student-service/'
      path: '/'
      fullPath: '/student-service/'
      preLoaderRoute: typeof StudentServiceIndexRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/guest/': {
      id: '/guest/'
      path: '/'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/director-academic/': {
      id: '/director-academic/'
      path: '/'
      fullPath: '/director-academic/'
      preLoaderRoute: typeof DirectorAcademicIndexRouteImport
      parentRoute: typeof DirectorAcademicRoute
    }
    '/dean/': {
      id: '/dean/'
      path: '/'
      fullPath: '/dean/'
      preLoaderRoute: typeof DeanIndexRouteImport
      parentRoute: typeof DeanRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-service/students': {
      id: '/student-service/students'
      path: '/students'
      fullPath: '/student-service/students'
      preLoaderRoute: typeof StudentServiceStudentsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/scholarships': {
      id: '/student-service/scholarships'
      path: '/scholarships'
      fullPath: '/student-service/scholarships'
      preLoaderRoute: typeof StudentServiceScholarshipsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/reports': {
      id: '/student-service/reports'
      path: '/reports'
      fullPath: '/student-service/reports'
      preLoaderRoute: typeof StudentServiceReportsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/populations': {
      id: '/student-service/populations'
      path: '/populations'
      fullPath: '/student-service/populations'
      preLoaderRoute: typeof StudentServicePopulationsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/orientation': {
      id: '/student-service/orientation'
      path: '/orientation'
      fullPath: '/student-service/orientation'
      preLoaderRoute: typeof StudentServiceOrientationRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/inscriptions': {
      id: '/student-service/inscriptions'
      path: '/inscriptions'
      fullPath: '/student-service/inscriptions'
      preLoaderRoute: typeof StudentServiceInscriptionsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/highschool-infos': {
      id: '/student-service/highschool-infos'
      path: '/highschool-infos'
      fullPath: '/student-service/highschool-infos'
      preLoaderRoute: typeof StudentServiceHighschoolInfosRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/documents': {
      id: '/student-service/documents'
      path: '/documents'
      fullPath: '/student-service/documents'
      preLoaderRoute: typeof StudentServiceDocumentsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/dashboard': {
      id: '/student-service/dashboard'
      path: '/dashboard'
      fullPath: '/student-service/dashboard'
      preLoaderRoute: typeof StudentServiceDashboardRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/clubs': {
      id: '/student-service/clubs'
      path: '/clubs'
      fullPath: '/student-service/clubs'
      preLoaderRoute: typeof StudentServiceClubsRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/activities': {
      id: '/student-service/activities'
      path: '/activities'
      fullPath: '/student-service/activities'
      preLoaderRoute: typeof StudentServiceActivitiesRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/student-service/absences': {
      id: '/student-service/absences'
      path: '/absences'
      fullPath: '/student-service/absences'
      preLoaderRoute: typeof StudentServiceAbsencesRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/guest/profile': {
      id: '/guest/profile'
      path: '/profile'
      fullPath: '/guest/profile'
      preLoaderRoute: typeof GuestProfileRouteImport
      parentRoute: typeof GuestRoute
    }
    '/guest/dashboard': {
      id: '/guest/dashboard'
      path: '/dashboard'
      fullPath: '/guest/dashboard'
      preLoaderRoute: typeof GuestDashboardRouteImport
      parentRoute: typeof GuestRoute
    }
    '/finance/wording': {
      id: '/finance/wording'
      path: '/wording'
      fullPath: '/finance/wording'
      preLoaderRoute: typeof FinanceWordingRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/feessheets': {
      id: '/finance/feessheets'
      path: '/feessheets'
      fullPath: '/finance/feessheets'
      preLoaderRoute: typeof FinanceFeessheetsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/dashbord': {
      id: '/finance/dashbord'
      path: '/dashbord'
      fullPath: '/finance/dashbord'
      preLoaderRoute: typeof FinanceDashbordRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/banks': {
      id: '/finance/banks'
      path: '/banks'
      fullPath: '/finance/banks'
      preLoaderRoute: typeof FinanceBanksRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/director-academic/dashboard': {
      id: '/director-academic/dashboard'
      path: '/dashboard'
      fullPath: '/director-academic/dashboard'
      preLoaderRoute: typeof DirectorAcademicDashboardRouteImport
      parentRoute: typeof DirectorAcademicRoute
    }
    '/dean/teachers': {
      id: '/dean/teachers'
      path: '/teachers'
      fullPath: '/dean/teachers'
      preLoaderRoute: typeof DeanTeachersRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/students': {
      id: '/dean/students'
      path: '/students'
      fullPath: '/dean/students'
      preLoaderRoute: typeof DeanStudentsRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/schedules': {
      id: '/dean/schedules'
      path: '/schedules'
      fullPath: '/dean/schedules'
      preLoaderRoute: typeof DeanSchedulesRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/results': {
      id: '/dean/results'
      path: '/results'
      fullPath: '/dean/results'
      preLoaderRoute: typeof DeanResultsRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/progress': {
      id: '/dean/progress'
      path: '/progress'
      fullPath: '/dean/progress'
      preLoaderRoute: typeof DeanProgressRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/programs': {
      id: '/dean/programs'
      path: '/programs'
      fullPath: '/dean/programs'
      preLoaderRoute: typeof DeanProgramsRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/exam': {
      id: '/dean/exam'
      path: '/exam'
      fullPath: '/dean/exam'
      preLoaderRoute: typeof DeanExamRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/deliberations': {
      id: '/dean/deliberations'
      path: '/deliberations'
      fullPath: '/dean/deliberations'
      preLoaderRoute: typeof DeanDeliberationsRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/dashboard': {
      id: '/dean/dashboard'
      path: '/dashboard'
      fullPath: '/dean/dashboard'
      preLoaderRoute: typeof DeanDashboardRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/courses': {
      id: '/dean/courses'
      path: '/courses'
      fullPath: '/dean/courses'
      preLoaderRoute: typeof DeanCoursesRouteImport
      parentRoute: typeof DeanRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys': {
      id: '/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AdminSurveysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/survey-responses': {
      id: '/admin/survey-responses'
      path: '/survey-responses'
      fullPath: '/admin/survey-responses'
      preLoaderRoute: typeof AdminSurveyResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/survey-builder': {
      id: '/admin/survey-builder'
      path: '/survey-builder'
      fullPath: '/admin/survey-builder'
      preLoaderRoute: typeof AdminSurveyBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configs': {
      id: '/admin/configs'
      path: '/configs'
      fullPath: '/admin/configs'
      preLoaderRoute: typeof AdminConfigsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account-review': {
      id: '/admin/account-review'
      path: '/account-review'
      fullPath: '/admin/account-review'
      preLoaderRoute: typeof AdminAccountReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account-requested': {
      id: '/admin/account-requested'
      path: '/account-requested'
      fullPath: '/admin/account-requested'
      preLoaderRoute: typeof AdminAccountRequestedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/': {
      id: '/admin/programs/'
      path: '/'
      fullPath: '/admin/programs/'
      preLoaderRoute: typeof AdminProgramsIndexRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/student-service/parents/list': {
      id: '/student-service/parents/list'
      path: '/parents/list'
      fullPath: '/student-service/parents/list'
      preLoaderRoute: typeof StudentServiceParentsListRouteImport
      parentRoute: typeof StudentServiceRoute
    }
    '/finance/payment/studentpaymentdetails': {
      id: '/finance/payment/studentpaymentdetails'
      path: '/payment/studentpaymentdetails'
      fullPath: '/finance/payment/studentpaymentdetails'
      preLoaderRoute: typeof FinancePaymentStudentpaymentdetailsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payment/paymentpromises': {
      id: '/finance/payment/paymentpromises'
      path: '/payment/paymentpromises'
      fullPath: '/finance/payment/paymentpromises'
      preLoaderRoute: typeof FinancePaymentPaymentpromisesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payment/paymentplan': {
      id: '/finance/payment/paymentplan'
      path: '/payment/paymentplan'
      fullPath: '/finance/payment/paymentplan'
      preLoaderRoute: typeof FinancePaymentPaymentplanRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payment/addpayment': {
      id: '/finance/payment/addpayment'
      path: '/payment/addpayment'
      fullPath: '/finance/payment/addpayment'
      preLoaderRoute: typeof FinancePaymentAddpaymentRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/auth/2fa/setup': {
      id: '/auth/2fa/setup'
      path: '/auth/2fa/setup'
      fullPath: '/auth/2fa/setup'
      preLoaderRoute: typeof Auth2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/2fa/login': {
      id: '/auth/2fa/login'
      path: '/auth/2fa/login'
      fullPath: '/auth/2fa/login'
      preLoaderRoute: typeof Auth2faLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs/list': {
      id: '/admin/programs/list'
      path: '/list'
      fullPath: '/admin/programs/list'
      preLoaderRoute: typeof AdminProgramsListRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/admin/programs/academic': {
      id: '/admin/programs/academic'
      path: '/academic'
      fullPath: '/admin/programs/academic'
      preLoaderRoute: typeof AdminProgramsAcademicRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/admin/configs/security': {
      id: '/admin/configs/security'
      path: '/security'
      fullPath: '/admin/configs/security'
      preLoaderRoute: typeof AdminConfigsSecurityRouteImport
      parentRoute: typeof AdminConfigsRoute
    }
    '/admin/configs/notifications': {
      id: '/admin/configs/notifications'
      path: '/notifications'
      fullPath: '/admin/configs/notifications'
      preLoaderRoute: typeof AdminConfigsNotificationsRouteImport
      parentRoute: typeof AdminConfigsRoute
    }
    '/admin/configs/interface': {
      id: '/admin/configs/interface'
      path: '/interface'
      fullPath: '/admin/configs/interface'
      preLoaderRoute: typeof AdminConfigsInterfaceRouteImport
      parentRoute: typeof AdminConfigsRoute
    }
    '/admin/configs/general': {
      id: '/admin/configs/general'
      path: '/general'
      fullPath: '/admin/configs/general'
      preLoaderRoute: typeof AdminConfigsGeneralRouteImport
      parentRoute: typeof AdminConfigsRoute
    }
  }
}

interface AdminConfigsRouteChildren {
  AdminConfigsGeneralRoute: typeof AdminConfigsGeneralRoute
  AdminConfigsInterfaceRoute: typeof AdminConfigsInterfaceRoute
  AdminConfigsNotificationsRoute: typeof AdminConfigsNotificationsRoute
  AdminConfigsSecurityRoute: typeof AdminConfigsSecurityRoute
}

const AdminConfigsRouteChildren: AdminConfigsRouteChildren = {
  AdminConfigsGeneralRoute: AdminConfigsGeneralRoute,
  AdminConfigsInterfaceRoute: AdminConfigsInterfaceRoute,
  AdminConfigsNotificationsRoute: AdminConfigsNotificationsRoute,
  AdminConfigsSecurityRoute: AdminConfigsSecurityRoute,
}

const AdminConfigsRouteWithChildren = AdminConfigsRoute._addFileChildren(
  AdminConfigsRouteChildren,
)

interface AdminProgramsRouteChildren {
  AdminProgramsAcademicRoute: typeof AdminProgramsAcademicRoute
  AdminProgramsListRoute: typeof AdminProgramsListRoute
  AdminProgramsIndexRoute: typeof AdminProgramsIndexRoute
}

const AdminProgramsRouteChildren: AdminProgramsRouteChildren = {
  AdminProgramsAcademicRoute: AdminProgramsAcademicRoute,
  AdminProgramsListRoute: AdminProgramsListRoute,
  AdminProgramsIndexRoute: AdminProgramsIndexRoute,
}

const AdminProgramsRouteWithChildren = AdminProgramsRoute._addFileChildren(
  AdminProgramsRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRequestedRoute: typeof AdminAccountRequestedRoute
  AdminAccountReviewRoute: typeof AdminAccountReviewRoute
  AdminConfigsRoute: typeof AdminConfigsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminProgramsRoute: typeof AdminProgramsRouteWithChildren
  AdminSurveyBuilderRoute: typeof AdminSurveyBuilderRoute
  AdminSurveyResponsesRoute: typeof AdminSurveyResponsesRoute
  AdminSurveysRoute: typeof AdminSurveysRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRequestedRoute: AdminAccountRequestedRoute,
  AdminAccountReviewRoute: AdminAccountReviewRoute,
  AdminConfigsRoute: AdminConfigsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminProgramsRoute: AdminProgramsRouteWithChildren,
  AdminSurveyBuilderRoute: AdminSurveyBuilderRoute,
  AdminSurveyResponsesRoute: AdminSurveyResponsesRoute,
  AdminSurveysRoute: AdminSurveysRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DeanRouteChildren {
  DeanCoursesRoute: typeof DeanCoursesRoute
  DeanDashboardRoute: typeof DeanDashboardRoute
  DeanDeliberationsRoute: typeof DeanDeliberationsRoute
  DeanExamRoute: typeof DeanExamRoute
  DeanProgramsRoute: typeof DeanProgramsRoute
  DeanProgressRoute: typeof DeanProgressRoute
  DeanResultsRoute: typeof DeanResultsRoute
  DeanSchedulesRoute: typeof DeanSchedulesRoute
  DeanStudentsRoute: typeof DeanStudentsRoute
  DeanTeachersRoute: typeof DeanTeachersRoute
  DeanIndexRoute: typeof DeanIndexRoute
}

const DeanRouteChildren: DeanRouteChildren = {
  DeanCoursesRoute: DeanCoursesRoute,
  DeanDashboardRoute: DeanDashboardRoute,
  DeanDeliberationsRoute: DeanDeliberationsRoute,
  DeanExamRoute: DeanExamRoute,
  DeanProgramsRoute: DeanProgramsRoute,
  DeanProgressRoute: DeanProgressRoute,
  DeanResultsRoute: DeanResultsRoute,
  DeanSchedulesRoute: DeanSchedulesRoute,
  DeanStudentsRoute: DeanStudentsRoute,
  DeanTeachersRoute: DeanTeachersRoute,
  DeanIndexRoute: DeanIndexRoute,
}

const DeanRouteWithChildren = DeanRoute._addFileChildren(DeanRouteChildren)

interface DirectorAcademicRouteChildren {
  DirectorAcademicDashboardRoute: typeof DirectorAcademicDashboardRoute
  DirectorAcademicIndexRoute: typeof DirectorAcademicIndexRoute
}

const DirectorAcademicRouteChildren: DirectorAcademicRouteChildren = {
  DirectorAcademicDashboardRoute: DirectorAcademicDashboardRoute,
  DirectorAcademicIndexRoute: DirectorAcademicIndexRoute,
}

const DirectorAcademicRouteWithChildren =
  DirectorAcademicRoute._addFileChildren(DirectorAcademicRouteChildren)

interface FinanceRouteChildren {
  FinanceBanksRoute: typeof FinanceBanksRoute
  FinanceDashbordRoute: typeof FinanceDashbordRoute
  FinanceFeessheetsRoute: typeof FinanceFeessheetsRoute
  FinanceWordingRoute: typeof FinanceWordingRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  FinancePaymentAddpaymentRoute: typeof FinancePaymentAddpaymentRoute
  FinancePaymentPaymentplanRoute: typeof FinancePaymentPaymentplanRoute
  FinancePaymentPaymentpromisesRoute: typeof FinancePaymentPaymentpromisesRoute
  FinancePaymentStudentpaymentdetailsRoute: typeof FinancePaymentStudentpaymentdetailsRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceBanksRoute: FinanceBanksRoute,
  FinanceDashbordRoute: FinanceDashbordRoute,
  FinanceFeessheetsRoute: FinanceFeessheetsRoute,
  FinanceWordingRoute: FinanceWordingRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  FinancePaymentAddpaymentRoute: FinancePaymentAddpaymentRoute,
  FinancePaymentPaymentplanRoute: FinancePaymentPaymentplanRoute,
  FinancePaymentPaymentpromisesRoute: FinancePaymentPaymentpromisesRoute,
  FinancePaymentStudentpaymentdetailsRoute:
    FinancePaymentStudentpaymentdetailsRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface GuestRouteChildren {
  GuestDashboardRoute: typeof GuestDashboardRoute
  GuestProfileRoute: typeof GuestProfileRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestDashboardRoute: GuestDashboardRoute,
  GuestProfileRoute: GuestProfileRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface StudentServiceRouteChildren {
  StudentServiceAbsencesRoute: typeof StudentServiceAbsencesRoute
  StudentServiceActivitiesRoute: typeof StudentServiceActivitiesRoute
  StudentServiceClubsRoute: typeof StudentServiceClubsRoute
  StudentServiceDashboardRoute: typeof StudentServiceDashboardRoute
  StudentServiceDocumentsRoute: typeof StudentServiceDocumentsRoute
  StudentServiceHighschoolInfosRoute: typeof StudentServiceHighschoolInfosRoute
  StudentServiceInscriptionsRoute: typeof StudentServiceInscriptionsRoute
  StudentServiceOrientationRoute: typeof StudentServiceOrientationRoute
  StudentServicePopulationsRoute: typeof StudentServicePopulationsRoute
  StudentServiceReportsRoute: typeof StudentServiceReportsRoute
  StudentServiceScholarshipsRoute: typeof StudentServiceScholarshipsRoute
  StudentServiceStudentsRoute: typeof StudentServiceStudentsRoute
  StudentServiceIndexRoute: typeof StudentServiceIndexRoute
  StudentServiceParentsListRoute: typeof StudentServiceParentsListRoute
}

const StudentServiceRouteChildren: StudentServiceRouteChildren = {
  StudentServiceAbsencesRoute: StudentServiceAbsencesRoute,
  StudentServiceActivitiesRoute: StudentServiceActivitiesRoute,
  StudentServiceClubsRoute: StudentServiceClubsRoute,
  StudentServiceDashboardRoute: StudentServiceDashboardRoute,
  StudentServiceDocumentsRoute: StudentServiceDocumentsRoute,
  StudentServiceHighschoolInfosRoute: StudentServiceHighschoolInfosRoute,
  StudentServiceInscriptionsRoute: StudentServiceInscriptionsRoute,
  StudentServiceOrientationRoute: StudentServiceOrientationRoute,
  StudentServicePopulationsRoute: StudentServicePopulationsRoute,
  StudentServiceReportsRoute: StudentServiceReportsRoute,
  StudentServiceScholarshipsRoute: StudentServiceScholarshipsRoute,
  StudentServiceStudentsRoute: StudentServiceStudentsRoute,
  StudentServiceIndexRoute: StudentServiceIndexRoute,
  StudentServiceParentsListRoute: StudentServiceParentsListRoute,
}

const StudentServiceRouteWithChildren = StudentServiceRoute._addFileChildren(
  StudentServiceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DeanRoute: DeanRouteWithChildren,
  DevelopmentRoute: DevelopmentRoute,
  DirectorAcademicRoute: DirectorAcademicRouteWithChildren,
  FeaturespageRoute: FeaturespageRoute,
  FinanceRoute: FinanceRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  HomeRoute: HomeRoute,
  NotFoundRoute: NotFoundRoute,
  PublicSurveysRoute: PublicSurveysRoute,
  StudentServiceRoute: StudentServiceRouteWithChildren,
  StudentportalRoute: StudentportalRoute,
  SurveyRoute: SurveyRoute,
  TeacherportalRoute: TeacherportalRoute,
  TestErrorsRoute: TestErrorsRoute,
  TimetableRoute: TimetableRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  Auth2faLoginRoute: Auth2faLoginRoute,
  Auth2faSetupRoute: Auth2faSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
