name: Deploy ums-web

on:
  push:
    branches:
      - develop  # Déploiement automatique sur develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout le repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Déploiement via SSH
      - name: SSH Deploy script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e  # Stop en cas d'erreur
            export HOME=/home/${{ secrets.SERVER_USER }}
            LOG_FILE="$HOME/deploy_ums.log"
            DATE=$(date '+%Y-%m-%d_%H-%M-%S')

            echo "-------------------------------------------------" | tee -a "$LOG_FILE"
            echo "🔹 Déploiement ums-web en development  déclenché depuis GitHub à $DATE" | tee -a "$LOG_FILE"

            # 🔹 Mail de démarrage
            echo -e "Le déploiement a démarré de development sur le serveur\nDate: $DATE" | mail -s "Déploiement ums-web development - DÉMARRÉ" ndabubahajanvier@gmail.com

            # 🔹 Lancer le script complet de déploiement
            if [ -f "$HOME/deploy_ums.sh" ]; then
              bash "$HOME/deploy_ums.sh"
            else
              echo "❌ Script deploy_ums.sh de development non trouvé dans $HOME" | tee -a "$LOG_FILE"
              echo -e "Échec : deploy_ums.sh non trouvé sur le serveur" | mail -s "Déploiement ums-web - ÉCHEC" ndabubahajanvier@gmail.com
              exit 1
            fi
